default_agent: WsTranslator_Agent
agents:
  WsTranslator_Agent:
    name: WsTranslator_Agent
    entrypoint: /Users/jsbang/Documents/workshop-translator/WsTranslator/src/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/jsbang/Documents/workshop-translator/WsTranslator/src
    aws:
      execution_role: arn:aws:iam::287870618970:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-dae93547eb
      execution_role_auto_create: true
      account: '287870618970'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-287870618970-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: WsTranslator-684NN3GG3O
      memory_arn: null
      memory_name: WsTranslator_Memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
